# crates/ucode-amd/Cargo.toml
[package]
name = "ucode-amd"
description = "AMD microcode container parsing, validation and serialisation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ucode-core.workspace = true
thiserror = { workspace = true, features = ["std"] }
zerocopy.workspace = true
sha2.workspace = true
